name: Build

on: [pull_request]

jobs:
    build-client:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.15.1]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Set-local-env
              run: echo NX_APP_DOMAIN=${{secrets.API_HOST}} >> client/apps/kadvisor-app/.local.env

            - name: Instal node_modules
              working-directory: ./client
              run: npm install

            - name: Check-format
              working-directory: ./client
              run: npm run format:check

            - name: Build
              working-directory: ./client
              run: npm run build:prod

            - name: Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: ./client/dist
                  retention-days: 5

    build-server:
        runs-on: ubuntu-latest
        needs: build-client
        strategy:
            matrix:
                go-version: [1.14.4]
        steps:
            - uses: actions/checkout@v2
            - name: Download client artifact
              uses: actions/download-artifact@v1
              with:
                  name: 'dist'
                  path: ./client/dist

            - name: Verify Artifact
              run: |
                  $file = "client/dist/apps/kadvisor-app/index.html"
                  if(!(Test-Path -path $file))
                  {
                      Write-Error "Expected file does not exist"
                  }
              shell: pwsh

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Build
              run: go build

            - name: Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: kadvisor
                  path: ./kadvisor
                  retention-days: 5

    build-docker:
        runs-on: ubuntu-latest
        needs: [build-client, build-server]
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2
            - name: Download server artifact
              uses: actions/download-artifact@v1
              with:
                  name: 'kadvisor'
                  path: ./kadvisor

            - name: Download client artifact
              uses: actions/download-artifact@v1
              with:
                  name: 'dist'
                  path: ./client/dist

            - name: Set up Docker Builder
              uses: docker/setup-buildx-action@v1

            - name: Log into GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push to Github Container Registry
              uses: docker/build-push-action@v2
              with:
                  context: .
                  version: latest
                  file: Dockerfile
                  push: true
                  tags: ghcr.io/${{ github.repository }}:latest
