name: Kadvisor-pipeline

on: [push]

jobs:
    build-client:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.15.1]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Set-local-env
              run: echo NX_APP_DOMAIN=${{secrets.API_HOST}} >> client/apps/kadvisor-app/.local.env

            - name: Instal node_modules
              working-directory: ./client
              run: npm install

            - name: Check-format
              working-directory: ./client
              run: npm run format:check

            - name: Build
              working-directory: ./client
              run: npm run build:prod

            - name: Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: ./client/dist
                  retention-days: 5

    build-server:
        runs-on: ubuntu-latest
        needs: build-client

        strategy:
            matrix:
                go-version: [1.14.4]

        steps:
            - uses: actions/checkout@v2

            - name: Download client artifact
              uses: actions/download-artifact@v1
              with:
                  name: 'dist'
                  path: ./client/dist

            - name: 'Verify Artifact'
              run: |
                  $file = "client/dist/apps/kadvisor-app/index.html"
                  if(!(Test-Path -path $file))
                  {
                      Write-Error "Expected file does not exist"
                  }
              shell: pwsh

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Build
              run: go build

            - name: Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: kadvisor
                  path: ./kadvisor
                  retention-days: 5
